### ISSUE TITLE
package version

### ISSUE THREAD

**Issue by chrisblossom** [BryceHQ/es3ify-webpack-plugin#1]
Thank you for releasing this. Would you mind setting a package version other than 0.0.0? Preferably follow semver and start with 1.0.0. I can put a PR in if you would like.

Thoughts?

**Comment by BryceHQ** [comment]
> version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

I think I already followed the rules. And I don't think 1.0.0 is a right choice.
If I have misunderstood anything, please let me know.

**Comment by chrisblossom** [comment]
Sorry, you are correct. I was just confused by the 0.0.0 so I assumed it was just over looked.

Thanks again for putting this out there!

**Comment by BryceHQ** [comment]
That's all right. I would be happy if it can help you.
