### ISSUE TITLE
webpack config

### ISSUE THREAD

**Issue by adam-26** [BryceHQ/es3ify-webpack-plugin#5]
Hi,
Maybe you have a special use-case, but es3ify can transform files in node_modules, you just need to configure it correctly. Is it possible that you have an 'exclude' condition that prevents the loader from transforming files in the node_modules directory?

Here is an example:

``` javascript
module: {
        loaders: [{
// Here, webpack is instructed to EXCLUDE the node_modules directory
          test: /\.js$/,
          exclude: /\/node_modules\//,
          loader: 'babel-loader'
          query: {
            presets: ['es2015'],
          }
        }, {
// Here you instruct webpack to use the es3ify loader for the node_modules directory
            test: /\.js$/,
            include: /\/node_modules\//,
            loader: 'es3ify'
        }]
      }
```

Was looking for a solution for the same problem when I saw your plugin, if you needed the plugin for other reasons then please ignore this :)

**Comment by BryceHQ** [comment]
Yes, you are right.
I didn't find the right way to use the es3ify loader.
Then it would be no point in this plugin.
