### ISSUE TITLE
Doesn't fix the code emitted by Webpack 3.x

### ISSUE THREAD

**Issue by buddyackerman** [BryceHQ/es3ify-webpack-plugin#6]
I still get Object,defineProperty in the output of my webpack bundle.  Was this plugin designed to fix that?  If not, what does this plugin accomplish as the code output by Webpack is still not runnable in IE8?

**Comment by BryceHQ** [comment]
Sorry, I haven't use Webpack 3.X .
I recommend you to use the es3ify-loader. [For detail.](https://github.com/BryceHQ/es3ify-webpack-plugin/issues/5)
