### ISSUE TITLE
webpack.optimize.UglifyJsPlugin 的sourceMap不选true就报错

### ISSUE THREAD

**Issue by xxssww0258** [BryceHQ/es3ify-webpack-plugin#7]
UglifyJsPlugin=new webpack.optimize.UglifyJsPlugin
if(UglifyJsPlugin)
{
if(UglifyJsPlugin.sourceMap==true){
throw 'error'
}else{
console.log('Webpack normal for pack')
}
}
```
ERROR in ./js/vendor.823775742b2101a960ae.js from es3ify
TypeError: Cannot read property 'sections' of null
```

**Comment by gnipbao** [comment]
同问？为什么

**Comment by BryceHQ** [comment]
抱歉才回复，建议使用 es3ify-loader. [For detail.](https://github.com/BryceHQ/es3ify-webpack-plugin/issues/5)
