### ISSUE TITLE
dont support webpack 4.x?

### ISSUE THREAD

**Issue by ireeoo** [BryceHQ/es3ify-webpack-plugin#9]
I tried this plugin in webpack 4.x,but nothing helped....

**Comment by BryceHQ** [comment]
Sorry, you should use es3ify-loader. [For detail.](https://github.com/BryceHQ/es3ify-webpack-plugin/issues/5)

**Comment by NongDeng** [comment]
webpack v4+ will minify your code by default in production mode. 

you can do it in your webpack.config.js and solve it:

![image](https://user-images.githubusercontent.com/7445615/61209338-0f622280-a72c-11e9-8f57-9fbd8f6499ed.png)
